### ISSUE TITLE
Download Button is not working in windows

### ISSUE THREAD

**Issue by UsmanLiaqat404** [vleerapp/Vleer#15]
I'm using Windows 11 and trying to download but nothing happens

![image](https://github.com/vleerapp/Vleer/assets/117591938/d7c77a12-07d1-4d54-a336-ef777671bf51)
![image](https://github.com/vleerapp/Vleer/assets/117591938/3645fc1d-0ae8-4d31-b9c8-f2dcd7e7fdec)

**Comment by 0PandaDEV** [comment]
That's because there is no download at the moment I should probably remove the download page or change it you can only compile it yourself right now, but I also have to say that the version that is currently in the main branch is completely bugged and not usable I'm working. But I'm working on a rewrite.
